modules/urls.py
from django.urls import path, re_path
from modules.views import ModuleListView,ImagesListView,SpellingListView, \
RepeatListView, AcademicVocabularyListView, DictationListView, \
HighlightListView, SelectMissingWordView, HighlightCorrectSummaryView, ReadAloudView, \
RetellLectureView, EssayView, FillInBlanksView, AnswerShortQuestionsView, ReorderParagraphView, \
MultipleSelectionView, MultipleSelectionReadingView, FillBlanksReadingView, SummarizeSpokenTextView,\
SummarizeWrittenTextView,QuestionSectionView, HomePageListView

urlpatterns = [
    
    path('',HomePageListView.as_view(),name='home'),
    path('speaking-describe-image/', ImagesListView.as_view(),name='describe-image'),
    path('writing-spelling/', SpellingListView.as_view(),name='common-spelling-mistakes'),
    path('speaking-repeat-sentence/', RepeatListView.as_view(),name='repeat-sentence'),
    path('writing-academic-vocabulary-builder/', AcademicVocabularyListView.as_view(),name='academic-vocabulary'),
    path('listening-write-from-dictation/', DictationListView.as_view(),name='write-dictation'),
    path('highlight-incorrect-words/', HighlightListView.as_view(),name='highlight-incorrect-words'),
    path('highlight-correct-summary/', HighlightCorrectSummaryView.as_view(),name='highlight-correct-summary'),
    path('listening-select-missing-word/', SelectMissingWordView.as_view(),name='select-missing-word'),
    path('speaking-read-aloud/', ReadAloudView.as_view(),name='read-aloud'),
    path('speaking-retell-lecture/', RetellLectureView.as_view(),name='re-tell-lecture'),
    path('writing-write-essay/',EssayView.as_view(),name='essay'),
    path('listening-fill-in-blanks/',FillInBlanksView.as_view(),name='fill-blanks'),
    path('speaking-answer-short-question/',AnswerShortQuestionsView.as_view(),name='answer-short-questions'),
    path('reading-reorder-paragraphs/',ReorderParagraphView.as_view(),name='re-order-paragraphs'),
    path('listening-multiple-selection/',MultipleSelectionView.as_view(),name='multiple-choice-questions'),
    path('reading-multiple-selection/',MultipleSelectionReadingView.as_view(),name='multiple-choice-questions-reading'),
    path('listening-fill-blanks/',FillBlanksReadingView.as_view(),name='fill-blanks-reading'),
    path('speaking-summarize-spoken-text/',SummarizeSpokenTextView.as_view(),name='summarize-spoken-text'),
    path('writing-summarize-written-text/',SummarizeWrittenTextView.as_view(),name='summarize-written-text'),
    
]

order/urls.py
from django.urls import path, re_path
from .views import OrderSummaryView, OrderCreateView

urlpatterns = [
    
    path('new_order', OrderSummaryView.as_view(),name='new_order'),
    path('order_create', OrderCreateView.as_view(),name='order_create'),

]

ptebooster/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from modules.views import HomePageListView
from modules.views import PageNotFoundView
from django.conf.urls import  handler404

from django.conf.urls.static import static

urlpatterns = [
    path('',HomePageListView.as_view(),name='index'),
    path('admin/', admin.site.urls),
    path('modules/', include('modules.urls')),
    path('account/', include('account.urls')),
    path('membership/', include('membership.urls')),
    path('purchase/', include('purchase.urls')),
    path('order/', include('order.urls')),
    path('dashboard/', include('dashboard.urls')),
    #path('contact/', include('contact.urls')),

]
handler404 = PageNotFoundView.as_view()

if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
User = get_user_model()
class ContactDataManager(models.Manager):
    def create_request(self,request_number,is_registered, is_paid_member, name, email, subject, message):
        request = self.create(
                            request_number=request_number,
                            is_registered=is_registered,
                            is_paid_member=is_paid_member,
                            name=name,
                            email=email,
                            subject=subject,
                            message=message
                            )
        return request
class ContactData(models.Model):
    request_number = models.CharField(primary_key=True, max_length=50)
    is_registered = models.BooleanField(default=False)
    is_paid_member = models.BooleanField(default=False)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    subject = models.CharField(max_length=150)
    message = models.CharField(max_length=1250)
    created_on = models.DateTimeField(auto_now_add=True)

    objects = ContactDataManager()

    
    def __str__(self):
        return self.request_number



class Notification(models.Model):
    subject = models.CharField(max_length=100, blank=False, null=False)
    body = models.TextField(max_length=1000, blank=False, null=False)
    receiver_id = models.IntegerField(null=True, default=0,validators=[MinValueValidator(0)],help_text="Enter user ID for a specific user. For bulk notification leave as it is.")
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User,on_delete=models.PROTECT ,limit_choices_to={'is_staff':True})

    objects = models.Manager() 
    @classmethod
    def create(cls,subject,body,receiver_id,created_by):
        notification = cls(subject=subject, body=body, receiver_id=receiver_id, created_by=created_by)
        notification.save()
    
    class Meta:
        indexes = [
            models.Index(fields=['receiver_id'], name='receiver_id_idx'),
            models.Index(fields=['created_on'],name='created_on_idx')
        ]

account/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.html import format_html


User = get_user_model()
class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','password')

class RegisterForm(forms.ModelForm):
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={'required':''}),
                                min_length=8, max_length=50, error_messages={'required':'Please enter your new password.'})

    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'required':''}), max_length=50, error_messages={'required':'Please re-enter your new password for confirmation.'})
    confirm_email = forms.CharField(widget=forms.TextInput(attrs={'required':''}),error_messages={'required':'Please confirm your email.'})
    class Meta:
        model = User
        fields = ('email','first_name','last_name')
        widgets = {
            
            'email': forms.TextInput(attrs=({'required': ''})),
            'first_name': forms.TextInput(attrs=({'required': ''})),
        }
        error_messages = {
            'username': {'required': 'Please choose a username.'},
            'first_name': {'required': 'Please enter your first name.'}

        }

    def clean_email(self):
        email = self.cleaned_data['email']

        if not email:
            raise ValidationError('Please enter your email address.')

        if User.objects.filter(email__iexact=email).exists():
            message = format_html('User with this Email account already exists.Please click <a href="{}">here</a> if you forgot your password', reverse('account_forgot_password'))
            raise ValidationError(message)
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        return username
    def clean_confirm_email(self):
        confirm_email = self.cleaned_data['confirm_email']
        if 'email' in self.cleaned_data and self.cleaned_data['email'] != confirm_email:
            raise forms.ValidationError("Emails do not match.")
        return confirm_email

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if not first_name:
            raise ValidationError('Please enter your first name.')
        return first_name
    def clean_confirm_password(self):
        confirm_password = self.cleaned_data['confirm_password']
        if 'password' in self.cleaned_data and self.cleaned_data['password'] != confirm_password:
            raise forms.ValidationError("Passwords do not match.")
        return confirm_password

class PasswordResetForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'required':''}),
                                min_length=8, max_length=50, error_messages={'required':'Please enter your new password.'})
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'required':''}), max_length=50, error_messages={'required':'Please re-enter your new password for confirmation.'})

    def clean_confirm_password(self):
        confirm_password = self.cleaned_data['confirm_password']
        if 'password' in self.cleaned_data and self.cleaned_data['password'] != confirm_password:
            raise forms.ValidationError("Your new password and confirm password didn't matched.")
        return confirm_password

class ForgottenPasswordForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data['email']
        return email
        
class ResendActivationForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data['email']
        return email

modules/forms.py
from django import forms
from membership.models import Membership

class BuyForm(forms.Form):
    member_type = forms.CharField(label='member_type', max_length=100)

   

modules/templates/scripts/answer-short-questions-js.html
 <!--answer short questions section -->
 <script>
   

    function showAnswer(){
      
      var answer = $('#answer').val().toLowerCase().trim();
      var useranswer = $('#useranswer').val().toLowerCase().trim();
      if (useranswer===""){
        $('#useranswer').addClass('alert-danger');
      }
      else if (answer !==useranswer){
        $('#useranswer').addClass('alert-danger');
        $('#answer').addClass('alert-danger');
        $('#answer').css('visibility','visible');
      }
      else{
        $('#useranswer').addClass('alert-success');
        $('#answer').css('visibility','visible');
      }
  
    }
    function playAnswer(){
      showAnswer();
      document.getElementById('answer').play();
    }
    </script>

<script>
  /* used by repeat sentence as well */
    function displayAnswer(){
      $('#answer').css('visibility','visible');
    }
  
  </script>

modules/templates/scripts/answer-short-questions.html
 <!--answer short questions section -->
 <script>
   

    function showAnswer(){
      
      var answer = $('#answer').val().toLowerCase().trim();
      var useranswer = $('#useranswer').val().toLowerCase().trim();
      if (useranswer===""){
        $('#useranswer').addClass('alert-danger');
      }
      else if (answer !==useranswer){
        $('#useranswer').addClass('alert-danger');
        $('#answer').addClass('alert-danger');
        $('#answer').css('visibility','visible');
      }
      else{
        $('#useranswer').addClass('alert-success');
        $('#answer').css('visibility','visible');
      }
  
    }
    function playAnswer(){
      showAnswer();
      document.getElementById('answer').play();
    }
    </script>

modules/templates/scripts/card-payment-js.html
<!-- Script for contact form starts -->

<script>

        $(document).ready(function(){
            $("#cardPayment").click(function (){
         function getCookie(name)
        {
           var cookieValue = null;
           if (document.cookie && document.cookie != '') {
               var cookies = document.cookie.split(';');
               for (var i = 0; i < cookies.length; i++) {
                   var cookie = jQuery.trim(cookies[i]);
                   // Does this cookie string begin with the name we want?
        
                   if (cookie.substring(0, name.length + 1) == (name + '=')) {
                       cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                       break;
                   }
               }
           }
           return cookieValue;
        }
         var fullname = $("#id_fullname").val();
         var cardnum = $("#id_cardnumber").val();
         var mm = $("#id_mm").val();
         var yy = $("#id_yy").val();
         var cvv = $("#id_cvv").val();
        //  alert('h')
         if ([fullname,cardnum,mm,yy,cvv].every(x => x.length>0)){
         $.ajax({
                 type : "POST",
                 url : '{% url "process_payment" %}',
                 data : {
                   csrfmiddlewaretoken : getCookie('csrftoken'),
                   'fullname' : fullname,
                   'cardnum' : cardnum,
                   'Exp_MM' : mm, 
                   'Exp_YY' : yy,
                   'cvv':cvv,
                   'payment_gateway':'ST',
                 },
                 success : function(){
                   $(".contactformalert").show();
                   $(".contactForm").hide();
                 }
         })}
        
        
        });});
        </script>
         <!-- Script for contact form ends -->

modules/templates/scripts/contact-form-js.html
<!-- Script for contact form starts -->

<script>

        $(".contactForm").on('submit',function(event){
         event.preventDefault();
         function getCookie(name)
        {
           var cookieValue = null;
           if (document.cookie && document.cookie != '') {
               var cookies = document.cookie.split(';');
               for (var i = 0; i < cookies.length; i++) {
                   var cookie = jQuery.trim(cookies[i]);
                   // Does this cookie string begin with the name we want?
        
                   if (cookie.substring(0, name.length + 1) == (name + '=')) {
                       cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                       break;
                   }
               }
           }
           return cookieValue;
        }
         var name = $("#id_name").val();
         var email = $("#id_email").val();
         var subject = $("#id_subject").val();
         var message = $("#id_message").val();
         if ([name,email,subject,message].every(x => x.length>0)){
         $.ajax({
                 type : "POST",
                 url : '{% url "home" %}',
                 data : {
                   csrfmiddlewaretoken : getCookie('csrftoken'),
                   'name' : name,
                   'email' : email,
                   'subject' : subject, 
                   'message' : message,
                 },
                 success : function(){
                   $(".contactformalert").show();
                   $(".contactForm").hide();
                 }
         })}
        
        
        })
        </script>
         <!-- Script for contact form ends -->

modules/templates/scripts/describe-image-js.html
<script>
/*  this part is for describe image */
$(function() {
  $('#showlecture').click(function(){
 
    if ($('.lecturerow').is(":hidden")){
      $('.lecturerow').css('display','inline');
      $('.lecturebadge').text('Hide Text');
    }else{
      $('.lecturerow').hide();
      $('.lecturebadge').text('Show Text');
    }
  })
  
  })
  /*  above part is for describe image */
  </script>

modules/templates/scripts/fill-blanks-reading-js.html
<!-- Fill in the blanks reading starts -->
<script>
        $(".fillReading").click(function(){
          var answers = new Array();
          $(".lanswer").each(function(){
            
            answers.push($(this).val().trim());
          })
          
          
          $(".introleadin").each(function(){
            var a = $(this).find("option:selected").text();
            var correctWord = $(this).closest('.correctword');
            $('.correctword').show();
           
            if (jQuery.inArray(a,answers) == -1){
        
           
              $(this).addClass('alert alert-danger');
            }else{
              
              $(this).addClass('alert alert-success ');
              
            }
          });
          $('.answerlist').show();
        });
        </script>
      <!-- Fill in the blanks ends-->

      <script>
        /* this scripts is used by listening and reading */
        $('#replacewords').each(function() {
          var text = $(this).text();
          $(this).text(text.replaceWith('XXXX', '<div class="col-xs-2"><input class="form-control" id="ex1" type="text"></div>')); 
      });
      
      
      </script>

modules/templates/scripts/fill-blanks-reading.html
<!-- Fill in the blanks reading starts -->
<script>
        $(".fillReading").click(function(){
          var answers = new Array();
          $(".lanswer").each(function(){
            
            answers.push($(this).val().trim());
          })
          
          
          $(".introleadin").each(function(){
            var a = $(this).find("option:selected").text();
            var correctWord = $(this).closest('.correctword');
            $('.correctword').show();
           
            if (jQuery.inArray(a,answers) == -1){
        
           
              $(this).addClass('alert alert-danger');
            }else{
              
              $(this).addClass('alert alert-success ');
              
            }
          });
          $('.answerlist').show();
        });
        </script>
      <!-- Fill in the blanks ends-->

modules/templates/scripts/highligh-incorrect-words-js.html
<!--highligh incorrect words section start-->
<script>
        $(".checkhighlight").click(function() {
          $(".actual").show();
          $(".clickable").each(function(){
            if ($(this).hasClass('crr')){
              $(this).addClass('alert alert-success');
      
            }else{
             
              if($(this).hasClass('alert alert-success')){
                $(this).addClass('alert alert-danger');
              }
            }
            $(this).off('click');
          });
      
        });
        
      </script>
      <script>
          $(".clickable").click(function() {
            
            var $el = $(this);
      
            
      
            if ( $el.hasClass('alert alert-success') ) {
              $el.removeClass('alert alert-success');
              
            }
            else {
              $el.addClass('alert alert-success');
         
            }
      
            
          
        });
          
        </script>
      
      <!--highligh incorrect words section end-->  

      <script> 
        /* this script is used by select missing word as well*/
          $(document).ready(function(){
          
          jQuery('.getvalue').on('click', function(e) {
          $('.message').css('visibility','visible');
          $('.message').show().text($("input:radio[name=optradio]:checked").val());
          if ($('#answer').text()==$("input:radio[name=optradio]:checked").val()){
            $('.message').removeClass('alert-danger').addClass('alert-success');
            
          }else{
          $('.message').removeClass('alert-success').addClass('alert-danger');
          $('.message').show().text($("input:radio[name=optradio]:checked").val());
          }
          });
          });
          
          </script>

modules/templates/scripts/highligh-incorrect-words.html
<!--highligh incorrect words section start-->
<script>
        $(".checkhighlight").click(function() {
          $(".actual").show();
          $(".clickable").each(function(){
            if ($(this).hasClass('crr')){
              $(this).addClass('alert alert-success');
      
            }else{
             
              if($(this).hasClass('alert alert-success')){
                $(this).addClass('alert alert-danger');
              }
            }
            $(this).off('click');
          });
      
        });
        
      </script>
      <script>
          $(".clickable").click(function() {
            
            var $el = $(this);
      
            
      
            if ( $el.hasClass('alert alert-success') ) {
              $el.removeClass('alert alert-success');
              
            }
            else {
              $el.addClass('alert alert-success');
         
            }
      
            
          
        });
          
        </script>
      
      <!--highligh incorrect words section end-->  

modules/templates/scripts/multiple-selection-js.html
<!-- Listening mutiple selection start-->
<script>
        $(".multipleCheck").click(function(){
          var answers= new Array;
          answers = $(".answers").val().split(',');
          
        
          $(".checkboxes input:checked").each(function(){
            var closediv = $(this).closest('.checkbox');
            
            if (jQuery.inArray($(this).val(),answers) == -1){
          
              closediv.addClass('bg-danger');
              
            }else{
              
              closediv.addClass('bg-success'); 
            }
          });
         
        });
        </script>
        <!-- Listening mutiple selection ends-->

modules/templates/scripts/read-aloud.html
<!-- Script for read aloud  starts hear-->
<script>
        var timeleft = document.getElementById("preparation").value;
        var startpoint = timeleft;
        var flipflop = 0;
        var downloadTimer = setInterval(function(){
          document.getElementById("progress").value = startpoint - --timeleft;
          document.getElementById("countdown").textContent = timeleft;
          if (timeleft===0 && flipflop===0){
            timeleft = 40;
            startpoint = 40;
            flipflop = 1;
            document.getElementById("progress").max = '40';
            document.getElementById("message").innerHTML = ' Recording ';
            
             }
             if (timeleft===0 && flipflop===1){
            var messageMain = document.getElementById("messageMain");
           
            messageMain.innerHTML = ' Done! ';
            
             }
          if(timeleft <= 0)
            clearInterval(downloadTimer);
            
        },1000);
        
        
    </script>
     <!-- Script for read aloud  ends hear-->

modules/templates/scripts/reorder-paragraph-js.html
<script>
        (function($) {
          var dragging, placeholders = $();
          $.fn.sortable = function(options) {
            var method = String(options);
            options = $.extend({
              connectWith: false
            }, options);
            return this.each(function() {
              if (/^enable|disable|destroy$/.test(method)) {
                var items = $(this).children($(this).data('items')).attr('draggable', method == 'enable');
                if (method == 'destroy') {
                  items.add(this).removeData('connectWith items')
                    .off('dragstart.h5s dragend.h5s selectstart.h5s dragover.h5s dragenter.h5s drop.h5s');
                }
                return;
              }
              var isHandle, index, items = $(this).children(options.items);
              var placeholder = $('<' + (/^ul|ol$/i.test(this.tagName) ? 'li' : 'div') + ' class="sortable-placeholder">');
              items.find(options.handle).mousedown(function() {
                isHandle = true;
              }).mouseup(function() {
                isHandle = false;
              });
              $(this).data('items', options.items)
              placeholders = placeholders.add(placeholder);
              if (options.connectWith) {
                $(options.connectWith).add(this).data('connectWith', options.connectWith);
              }
              items.attr('draggable', 'true').on('dragstart.h5s', function(e) {
                if (options.handle && !isHandle) {
                  return false;
                }
                isHandle = false;
                var dt = e.originalEvent.dataTransfer;
                dt.effectAllowed = 'move';
                dt.setData('Text', 'dummy');
                index = (dragging = $(this)).addClass('sortable-dragging').index();
              }).on('dragend.h5s', function() {
                if (!dragging) {
                  return;
                }
                dragging.removeClass('sortable-dragging').show();
                placeholders.detach();
                if (index != dragging.index()) {
                  dragging.parent().trigger('sortupdate', {item: dragging});
                }
                dragging = null;
              }).not('a[href], img').on('selectstart.h5s', function() {
                this.dragDrop && this.dragDrop();
                return false;
              }).end().add([this, placeholder]).on('dragover.h5s dragenter.h5s drop.h5s', function(e) {
                if (!items.is(dragging) && options.connectWith !== $(dragging).parent().data('connectWith')) {
                  return true;
                }
                if (e.type == 'drop') {
                  e.stopPropagation();
                  placeholders.filter(':visible').after(dragging);
                  dragging.trigger('dragend.h5s');
                  return false;
                }
                e.preventDefault();
                e.originalEvent.dataTransfer.dropEffect = 'move';
                if (items.is(this)) {
                  if (options.forcePlaceholderSize) {
                    placeholder.height(dragging.outerHeight());
                  }
                  dragging.hide();
                  $(this)[placeholder.index() < $(this).index() ? 'after' : 'before'](placeholder);
                  placeholders.not(placeholder).detach();
                } else if (!placeholders.is(this) && !$(this).children(options.items).length) {
                  placeholders.detach();
                  $(this).append(placeholder);
                }
                return false;
              });
            });
          };
          })(jQuery);
          
          
          
          
          $(function() {
                $('.sortable').sortable();
                $('.handles').sortable({
                  handle: 'span'
                });
                $('.connected').sortable({
                  connectWith: '.connected'
                });
                $('.exclude').sortable({
                  items: ':not(.disabled)'
                });
              });
    </script>

<script>
  $(".checkParagraph").click(function(){
    var answers = new Array();
    $(".answerlist").each(function(){
      
      answers.push($(this).val());
    })
   
    $("#list2 li").each(function(i){
      
      if ($(this).attr('value')===answers[i]){
        
        $(this).css('background-color','green');
      }else{
        $(this).css('background-color','red');
      }
      i+=1
    });
    
  });

</script>

modules/templates/scripts/retell-lecture-js.html
<script>
  var timeleft = document.getElementById("intro").value;
  var prog = document.getElementById("prog");
  var display = document.getElementById("display");
  var messageMain = document.getElementById("messageMain");
  var startpoint = timeleft;
  var flipflop = 0;
  var audioElement = document.getElementById('question');
  var downloadTimer = setInterval(function(){
  document.getElementById("prog").value = startpoint - --timeleft;
  document.getElementById("countdowntimer").textContent = timeleft;
    if (timeleft===0 && flipflop===0){
                        var duration = Math.round(audioElement.duration)
                        timeleft = duration;
                        startpoint = duration;
                        prog.max = duration;
                        display.innerHTML = 'Playing...';
                        audioElement.play();
                        flipflop = 1;
       }
    if (timeleft===0 && flipflop===1){
                        timeleft = 10;
                        startpoint = 10;
                        flipflop = 2;
                        prog.max = '10';
                        display.innerHTML = 'Recording in ';
     
      
       }
    if (timeleft===0 && flipflop===2){
                        duration = 40;
                        timeleft = duration;
                        startpoint = duration;
                        flipflop = 3;
                        prog.max = duration;
                        display.innerHTML = 'Recording...';
     
      
       }
    if (timeleft===0 && flipflop===3){
                        
                        messageMain.innerHTML = ' Done! ';
                        var button = document.getElementById('button_play');
                       
                        button.removeAttribute('disabled');
            
             }
    if(timeleft <= 0)
                        clearInterval(downloadTimer);
      
  },1000);
  

  function playModelAnswer(){
    var answer = document.getElementById('modelanswer')
    answer.play();

  }
  function StopModelAnswer(){
    var answer = document.getElementById('modelanswer')
    answer.pause();

  }
  $(function() {
  $('#showlecture').click(function(){
   
    if ($('.lecturerow').is(":hidden")){
      $('.lecturerow').css('display','inline');
      $('.lecturebadge').text('Hide Text');
    }else{
      $('.lecturerow').hide();
      $('.lecturebadge').text('Show Text');
    }
  })
  
  })

  
</script>

modules/templates/scripts/timing-all-js.html
<script>
        var timeleft = document.getElementById("seconds").value;
        console.log(timeleft)
        var downloadTimer = setInterval(function(){
          document.getElementById("progressBar").value = 8 - --timeleft;
          document.getElementById("countdowntimer").textContent = timeleft;
          if (timeleft===0){
            document.getElementById("audioContent").play();
            
             }
          if(timeleft <= 0)
            clearInterval(downloadTimer);
            
        },1000);
        
        
    </script>
    
    <script>
            function startTimer(duration, display) {
              var timer = duration, minutes, seconds;
              var timerId = setInterval(function () {
                  minutes = parseInt(timer / 60, 10)
                  seconds = parseInt(timer % 60, 10);
          
                  minutes = minutes < 10 ? "0" + minutes : minutes;
                  seconds = seconds < 10 ? "0" + seconds : seconds;
          
                  display.text(minutes + ":" + seconds);
          
                  if (--timer < 0) {
                     clearInterval(timerId);
                      $(".essaytextarea").attr('readonly',true);
                  }
                 
              }, 1000);
          }
          
          $( document ).ready(function () {
            var flipflop = 0;
              var minutes = parseInt($('#time').text().substr(0, 2));
              
              var givenMinutes = 60 * minutes,
                  display = $('#time');
                  
              startTimer(givenMinutes, display);
          });
           </script>
        
        
    