order/urls.py
from django.urls import path, re_path
from .views import OrderSummaryView, OrderCreateView

urlpatterns = [
    
    path('new_order', OrderSummaryView.as_view(),name='new_order'),
    path('order_create', OrderCreateView.as_view(),name='order_create'),

]

ptebooster/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from modules.views import HomePageListView
from modules.views import PageNotFoundView
from django.conf.urls import  handler404

from django.conf.urls.static import static

urlpatterns = [
    path('',HomePageListView.as_view(),name='index'),
    path('admin/', admin.site.urls),
    path('modules/', include('modules.urls')),
    path('account/', include('account.urls')),
    path('membership/', include('membership.urls')),
    path('purchase/', include('purchase.urls')),
    path('order/', include('order.urls')),
    path('dashboard/', include('dashboard.urls')),
    #path('contact/', include('contact.urls')),

]
handler404 = PageNotFoundView.as_view()

if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models
from ptebooster import settings
from membership.models import Membership
from django.utils.crypto import get_random_string

class OrderManager(models.Manager):
    def order(self,user,total,membership_type):
        order_number = get_random_string(12)

        order = self.create(
            customer=user,
            total=total,
            membership_type=membership_type,
            order_status='PE',
            payment_status='PE',
            order_number=order_number
        )
class Order(models.Model):
    
    ORDER_PENDING = 'PE'
    ORDER_PROCESSING = 'PR'
    ORDER_COMPLETE = 'CO'
    ORDER_CANCELLED = 'CA'
    ORDER_STATUSES = ((ORDER_PENDING, 'Pending'),
                      (ORDER_PROCESSING, 'Processing'),
                      (ORDER_COMPLETE, 'Complete'),
                      (ORDER_CANCELLED, 'Cancelled'))

    # Payment statuses
    PAYMENT_PENDING = 'PE'
    PAYMENT_AUTHORIZED = 'AU'
    PAYMENT_PAID = 'PA'
    PAYMENT_PARTIALLY_REFUNDED = 'PR'
    PAYMENT_REFUNDED = 'RE'
    PAYMENT_VOID = 'VO'
    PAYMENT_STATUSES = ((PAYMENT_PENDING, 'Pending'),
                        (PAYMENT_AUTHORIZED, 'Authorized'),
                        (PAYMENT_PAID, 'Paid'),
                        (PAYMENT_PARTIALLY_REFUNDED, 'Partially Refunded'),
                        (PAYMENT_REFUNDED, 'Refunded'),
                        (PAYMENT_VOID, 'Void'))

    customer = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,unique=False)
    total = models.DecimalField(max_digits=9, decimal_places=2)
    membership_type = models.ForeignKey(Membership,on_delete=models.PROTECT, null=True, blank=True)
    order_status = models.CharField(max_length=15, choices=ORDER_STATUSES)
    payment_status = models.CharField(max_length=15, choices=PAYMENT_STATUSES)
    order_number = models.CharField(max_length=100)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)

    objects = OrderManager()
    class Meta:
        indexes = [
            models.Index(fields=['customer'], name='order_idx'),
            models.Index(fields=['created_on'], name='order_created_on_idx'),
        ]
    def __str__(self):
        return self.order_number
    
    

order/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from membership.models import Membership

User = get_user_model()


class OrderForm(forms.ModelForm):
    member_type = forms.ModelChoiceField(queryset=Membership.objects.all().order_by('is_active'))
    class Meta:
        model = Membership
        fields = (
                  'price',
                  'duration',
                  'total_listening_question',
                  'total_reading_question',
                  'total_speaking_question',
                  'total_writing_question',
                  )
        widgets = {
            'price' : forms.TextInput(attrs=({'readonly':'readonly'})),
            'duration' : forms.TextInput(attrs=({'readonly':'readonly'})),
            'total_listening_question' : forms.TextInput(attrs=({'readonly':'readonly'})),
            'total_reading_question' : forms.TextInput(attrs=({'readonly':'readonly'})),
            'total_speaking_question' : forms.TextInput(attrs=({'readonly':'readonly'})),
            'total_writing_question' : forms.TextInput(attrs=({'readonly':'readonly'})),
        }

    def clean_member_type(self):
        member_type = self.cleaned_data['member_type']
        return member_type


class InitialOrderForm(forms.Form):
    member_type = forms.CharField(label='member_type', max_length=100)

order/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import redirect
from django.views.generic import ListView, View
from .forms import OrderForm, InitialOrderForm
from modules.forms import BuyForm
from membership.models import Membership
from .models import Order
from purchase.models import Gateway
from contact.notification_texts import ORDER_ERROR_1
from  stats.models import QuestionStatistics
# Create your views here.

class OrderSummaryView(ListView):
    model = Membership
    page_title = 'New Order'
    template_name = 'order/new_order.html'

    def get_context_data(self, **kwargs):
        member_type = self.request.GET.get('member_type','')
        membership = Membership.objects.get(member_type=member_type)
        print('ah',QuestionStatistics.objects.filter(membership_type=member_type, is_active=True, question_section='Listening').count())     
        context = super(OrderSummaryView, self).get_context_data( **kwargs)
        context.update({
            'object' : membership,
            'listening' : QuestionStatistics.objects.filter(membership_type__presedence__lte=membership.presedence, is_active=True, question_section='Listening').count(),
            'reading' : QuestionStatistics.objects.filter(membership_type__presedence__lte=membership.presedence, is_active=True, question_section='Reading').count(),
            'speaking' : QuestionStatistics.objects.filter(membership_type__presedence__lte=membership.presedence, is_active=True, question_section='Speaking').count(),
            'writing' : QuestionStatistics.objects.filter(membership_type__presedence__lte=membership.presedence, is_active=True, question_section='Writing').count(),
        })
        return context
    def get(self,request):
        return super(OrderSummaryView,self).get(request) 

    def post(self, request, *args, **kwargs):
        error = None      
        form = BuyForm(request.POST)
        if form.is_valid():
            try:
                data = form.cleaned_data
                obj= Membership.objects.get(member_type=data['member_type'])
                try:
                    Order.objects.order(self.request.user,obj.price,obj)
                    
            
                    return redirect('order_create')
                except Exception:
                    error = ORDER_ERROR_1
            except Exception:
                error = ORDER_ERROR_1 
        else:
            error = ORDER_ERROR_1
        return render(request,'order/new_order.html', {'error':error})
class OrderCreateView(ListView):
    # revise this class later
    model = Order 
    template_name = 'purchase/checkout.html'

    def get_context_data(self, **kwargs):
        order = Order.objects.filter(customer=self.request.user).order_by('-created_on')[0]
        gateways = Gateway.objects.filter(is_active=True)
        return super(OrderCreateView, self).get_context_data(gateways=gateways, order=order, **kwargs)
        
    def get(self,request):
        return super(OrderCreateView,self).get(request)

   
        

order/templates/order/new_order.html
{% extends "base.html" %}

{% block content %}
<br>
<br>
	
<!--==========================
    Pricing Table Section
  ============================-->
  <section id="pricing" class="padd-section text-center wow fadeInUp">

    <div class="container">
      <div class="section-title text-center">

        <h2>Order Summary</h2>
        <p class="separator">Integer cursus bibendum augue ac cursus.</p>
      </div>
    </div>

    <div class="container text-left">
        <dl class="row border">
          
            <dt class="col-sm-3">Memebership Type</dt>
            <dd class="col-sm-9">{{ object.member_type}}</dd>
            <dt class="col-sm-3">Price</dt>
            <dd class="col-sm-9">
              <p>{% if object.price == 0.0 %}Free{% else %}{{ object.price}}{% endif %}</p>  
            </dd>
            <dt class="col-sm-3">Number of Questions</dt>
            <dd class="col-sm-9">
                <p>Listening : {{ listening}}</p>
                <p>Reading : {{ reading }}</p>
                <p>Writing : {{ writing }}</p>
                <p>Speaking : {{ speaking}}</p>
            </dd>
            <dt class="col-sm-3 text-truncate">Terms and Conditions</dt>
            <dd class="col-sm-9 text-justify">
                <p>In every part of the question types (Listening, Rading, Writing and Speaking), the number of Questions
                  of sub-sections(such as "Read Aloud", "Repeat Sentence", "Answer Short Questions") can vary. 
                </p>
                <p>Because of digital material provided in this website, refund won't be possible.</p>
                <p>The latest version of common browsers such as Chrome, Firefox should be used to be able to benefit from this website with minimal techniqual difficulties. </p>
                <p>By clicking the "Checkout" button, terms and conditions shall be accepted.</p>
            </dd>
          </dl>
    </div>
    <br>
    <div class="table_btn">
        {% if object.price == 0.0 %}
        <a href="{% url 'dashboard' %}" class="btn"><i class="fa fa-shopping-cart"></i> Practice</a>
        
        {% else %}
        <form action="{% url 'new_order' %}" method="POST" >
          {% csrf_token %}
          <input type="hidden" name="member_type" id="id_member_type" value="{{ object.member_type}}" >
        <button type="submit" class="btn btn-success"><i class="fa fa-shopping-cart"></i> Checkout</a>
        </form>
        {% endif %}
      </div></div>
  </section>
{% endblock %}